name: Autograding Tests
'on':
  push:
    paths:
      - "app/**"
      - "public/**"
      - "resources/**"
      - "routes/**"
      - "tests/**"
      - "config/**"
  workflow_dispatch:

env:
  # test-NNNNNN: ランダムな数字6桁を付けて重複を回避させる
  project_name: test-${{ github.run_id }}
  LANG: ja_JP.UTF-8
  CONTAINE_USER: vscode

permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    # - name: echo project_name
    #   run: |
    #     echo ==============================
    #     echo ${{ env.project_name }}
    #     echo ==============================

    - name: Checkout code
      uses: actions/checkout@v4

    - name: SECRETから.envファイルを作成
      run: |
        # GH SecretのDOTENV変数に.envがまるのまま入っているのでリダイレクトで作成する
        echo "${{ secrets.DOTENV }}" > .env
    - name: コンテナの起動
      run: docker compose -p ${{ env.project_name }} -f compose.yml -f compose_test.yml up -d --quiet-pull
    - name: 結果画像の削除
      run: |
        rm -vf results/*.png
    - name: リポジトリの所有者を変更
      run: |
        docker compose -p ${{ env.project_name }} exec app sudo chown -R ${{ env.CONTAINE_USER }} /app

    - name: データベースへの接続テスト
      id: dbcheck
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: dbcheck
        setup-command: 'docker compose ps'
        command: 'docker compose  -p ${{ env.project_name }} exec app make test FILE=tests/test_db_connect.py'
        max-score: 1
        timeout: 2
    - name: トップページの表示テスト
      id: toppage
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: toppage
        command: 'docker compose -p ${{ env.project_name }} exec app make test FILE=tests/test_minishop_toppage.py'
        max-score: 1
        timeout: 2
    # - name: 結果画像の場所確認
    #   if: always()
    #   run: |
    #     find `pwd` -type f | sort

    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        DBCHECK_RESULTS: "${{steps.dbcheck.outputs.result}}"
        TOPPAGE_RESULTS: "${{steps.toppage.outputs.result}}"
      with:
        runners: dbcheck,toppage

    - name: 結果画像の一覧作成
      run: |
        echo ARTIFACTS=$(find results -type f -name "*.png") >> $GITHUB_ENV
    - name: 画像ファイルのアーティファクト化
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: result-images
        path: |
          ${{ env.ARTIFACTS }}
    - name: コンテナの停止
      if: always()
      run: docker compose  -p ${{ env.project_name }} down --rmi=local -v --timeout=3
    # - name: check files
    #   if: always()
    #   run: pwd; ls -l results
